version: "3.8"

services:
  app:
    image: randomportfolio
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
    - db
    ports:
      - "3000:80"
    volumes:
     - .:/usr/src
    command: npx nodemon index.js

  db:
    image: mongo